version: '3.8'
services:
  frontend:
    image: "docker.pkg.github.com/tolstoyfafa/lory-faycal/frontend:${APP_VERSION}"
    restart: always
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.docker.localhost`)"
      - "traefik.docker.network=${DC_EXEC_DIR}_gateway-frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=http"
    networks:
      - gateway-frontend
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "${HTTP_ENTRYPOINT_TRAEFIK_PORT:-80}:80"
      # The Web UI (enabled by --api.insecure=true)
      - "${TRAEFIK_ENTRYPOINT_TRAEFIK_PORT:-8080}:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gateway-external
      - gateway-backend
      - gateway-frontend
  backend: 
    image: "docker.pkg.github.com/tolstoyfafa/lory-faycal/backend:${APP_VERSION}"
    restart: always
    depends_on:
      - mysql
    labels: 
      - "traefik.http.routers.backend.rule=Host(`backend.docker.localhost`)"
      - "traefik.http.middlewares.back-mid.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.back-mid.headers.accesscontrolalloworiginlist=http://frontend.docker.localhost"
      - "traefik.docker.network=${DC_EXEC_DIR}_gateway-backend"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.middlewares=back-mid"
    networks:
      - gateway-backend
      - backend
    secrets:
      - secret_dec

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_dec
      - MYSQL_USER=myuser
      - MYSQL_DATABASE=mydb
    networks:
      - backend
    secrets:
      - secret_dec

secrets:
  secret_dec:
     file: ./mysecret.txt

networks:
  gateway-external:
    internal: false
  gateway-backend:
    internal: true
  gateway-frontend:
    internal: true
  backend:
    internal: true
