version: '3.8'
services:
  frontend:
    image: nginx:1.19
#    ports:
#      - "80:5000"
    volumes:
      - ./frontend:/usr/share/nginx/html
    labels:  
      - "traefik.http.routers.frontend.rule=Host(docker.frontend.localhost)"
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
